version: "3"

services:
  element:
    build:
      context: ./
    networks:
      - prospect_element
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: 'always'
    ports:
      - "${PORT}:80"
    volumes:
      - ${SITE_DIR}:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
networks:
  prospect_element:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.${SITE_ID}.0/24
